
# added by Anaconda3 5.0.1 installer
export PATH="/Users/allar-alexeyalexandrovich/anaconda3/bin:$PATH"

test() {
    mkdir ./AllarRouter/Modules/Flow/$@
    mkdir ./AllarRouter/Modules/Flow/$@/vmDA
    mkdir ./AllarRouter/Modules/Flow/$@/vcDA
    cd ./AllarRouter/Modules/Flow/$@
    
    now=$(date +%d.%m.%y)
    
    touch "$@VC🄲.swift"
    echo "//" >> "$@VC🄲.swift"
    echo "// $@VC🄲" >> "$@VC🄲.swift"
    echo "// $now"  >> "$@VC🄲.swift"
    echo "//"  >> "$@VC🄲.swift"
    echo ""  >> "$@VC🄲.swift"
    echo "import Foundation"  >> "$@VC🄲.swift"
    echo ""  >> "$@VC🄲.swift"
    echo "class $@VC🄲: CommandsVC🄲 {"  >> "$@VC🄲.swift"
    echo "}"  >> "$@VC🄲.swift"
    
    touch "$@VM🄲.swift"
    echo "//" >> "$@VM🄲.swift"
    echo "// $@VM🄲" >> "$@VM🄲.swift"
    echo "// $now"  >> "$@VM🄲.swift"
    echo "//"  >> "$@VM🄲.swift"
    echo ""  >> "$@VM🄲.swift"
    echo "import Foundation"  >> "$@VM🄲.swift"
    echo ""  >> "$@VM🄲.swift"
    echo "class $@VM🄲: CommandsVC🄲 {"  >> "$@VM🄲.swift"
    echo "}"  >> "$@VM🄲.swift"
    
    cd ./vcDA
    
    touch "$@VС🄲ID🄲.swift"
    echo "//" >> "$@VС🄲ID🄲.swift"
    echo "// $@VС🄲ID🄲" >> "$@VС🄲ID🄲.swift"
    echo "// $now"  >> "$@VС🄲ID🄲.swift"
    echo "//"  >> "$@VС🄲ID🄲.swift"
    echo ""  >> "$@VС🄲ID🄲.swift"
    echo "import Foundation"  >> "$@VС🄲ID🄲.swift"
    echo ""  >> "$@VС🄲ID🄲.swift"
    echo "class $@VС🄲ID🄲: InputData {"  >> "$@VС🄲ID🄲.swift"
    echo "}"  >> "$@VС🄲ID🄲.swift"
    
    touch "$@VC🄲IA🄲.swift"
    echo "//" >> "$@VC🄲IA🄲.swift"
    echo "// $@VC🄲IA🄲" >> "$@VC🄲IA🄲.swift"
    echo "// $now"  >> "$@VC🄲IA🄲.swift"
    echo "//"  >> "$@VC🄲IA🄲.swift"
    echo ""  >> "$@VC🄲IA🄲.swift"
    echo "import Foundation"  >> "$@VC🄲IA🄲.swift"
    echo ""  >> "$@VC🄲IA🄲.swift"
    echo "class $@VC🄲IA🄲: InputActions {"  >> "$@VC🄲IA🄲.swift"
    echo "}"  >> "$@VC🄲IA🄲.swift"
    
    touch "$@VC🄲OA🄲.swift"
    echo "//" >> "$@VC🄲OA🄲.swift"
    echo "// $@VC🄲OA🄲" >> "$@VC🄲OA🄲.swift"
    echo "// $now"  >> "$@VC🄲OA🄲.swift"
    echo "//"  >> "$@VC🄲OA🄲.swift"
    echo ""  >> "$@VC🄲OA🄲.swift"
    echo "import Foundation"  >> "$@VC🄲OA🄲.swift"
    echo ""  >> "$@VC🄲OA🄲.swift"
    echo "class $@VC🄲OA🄲: OutputActions {"  >> "$@VC🄲OA🄲.swift"
    echo "}"  >> "$@VC🄲OA🄲.swift"
    
    touch "$@VC🄲OD🄲.swift"
    echo "//" >> "$@VC🄲OD🄲.swift"
    echo "// $@VC🄲OD🄲" >> "$@VC🄲OD🄲.swift"
    echo "// $now"  >> "$@VC🄲OD🄲.swift"
    echo "//"  >> "$@VC🄲OD🄲.swift"
    echo ""  >> "$@VC🄲OD🄲.swift"
    echo "import Foundation"  >> "$@VC🄲OD🄲.swift"
    echo ""  >> "$@VC🄲OD🄲.swift"
    echo "class $@VC🄲OD🄲: OutputData {"  >> "$@VC🄲OD🄲.swift"
    echo "}"  >> "$@VC🄲OD🄲.swift"
    
    touch "$@VC🄲PA🄲.swift"
    echo "//" >> "$@VC🄲PA🄲.swift"
    echo "// $@VC🄲PA🄲" >> "$@VC🄲PA🄲.swift"
    echo "// $now"  >> "$@VC🄲PA🄲.swift"
    echo "//"  >> "$@VC🄲PA🄲.swift"
    echo ""  >> "$@VC🄲PA🄲.swift"
    echo "import Foundation"  >> "$@VC🄲PA🄲.swift"
    echo ""  >> "$@VC🄲PA🄲.swift"
    echo "class $@VC🄲PA🄲: PrivateActions {"  >> "$@VC🄲PA🄲.swift"
    echo "}"  >> "$@VC🄲PA🄲.swift"
    
    touch "$@VC🄲PD🄲.swift"
    echo "//" >> "$@VC🄲PD🄲.swift"
    echo "// $@VC🄲PD🄲" >> "$@VC🄲PD🄲.swift"
    echo "// $now"  >> "$@VC🄲PD🄲.swift"
    echo "//"  >> "$@VC🄲PD🄲.swift"
    echo ""  >> "$@VC🄲PD🄲.swift"
    echo "import Foundation"  >> "$@VC🄲PD🄲.swift"
    echo ""  >> "$@VC🄲PD🄲.swift"
    echo "class $@VC🄲PD🄲: PrivateData {"  >> "$@VC🄲PD🄲.swift"
    echo "}"  >> "$@VC🄲PD🄲.swift"
    
    cd -
    cd ./vmDA
    touch "$@VM🄲ID🄲.swift"
    echo "//" >> "$@VM🄲ID🄲.swift"
    echo "// $@VM🄲ID🄲" >> "$@VM🄲ID🄲.swift"
    echo "// $now"  >> "$@VM🄲ID🄲.swift"
    echo "//"  >> "$@VM🄲ID🄲.swift"
    echo ""  >> "$@VM🄲ID🄲.swift"
    echo "import Foundation"  >> "$@VM🄲ID🄲.swift"
    echo ""  >> "$@VM🄲ID🄲.swift"
    echo "class $@VM🄲ID🄲: InputData {"  >> "$@VM🄲ID🄲.swift"
    echo "}"  >> "$@VM🄲ID🄲.swift"
    
    touch "$@VM🄲IA🄲.swift"
    echo "//" >> "$@VM🄲IA🄲.swift"
    echo "// $@VM🄲IA🄲" >> "$@VM🄲IA🄲.swift"
    echo "// $now"  >> "$@VM🄲IA🄲.swift"
    echo "//"  >> "$@VM🄲IA🄲.swift"
    echo ""  >> "$@VM🄲IA🄲.swift"
    echo "import Foundation"  >> "$@VM🄲IA🄲.swift"
    echo ""  >> "$@VM🄲IA🄲.swift"
    echo "class $@VM🄲IA🄲: InputActions {"  >> "$@VM🄲IA🄲.swift"
    echo "}"  >> "$@VM🄲IA🄲.swift"
    
    touch "$@VM🄲OA🄲.swift"
    echo "//" >> "$@VM🄲OA🄲.swift"
    echo "// $@VM🄲OA🄲" >> "$@VM🄲OA🄲.swift"
    echo "// $now"  >> "$@VM🄲OA🄲.swift"
    echo "//"  >> "$@VM🄲OA🄲.swift"
    echo ""  >> "$@VM🄲OA🄲.swift"
    echo "import Foundation"  >> "$@VM🄲OA🄲.swift"
    echo ""  >> "$@VM🄲OA🄲.swift"
    echo "class $@VM🄲OA🄲: OutputActions {"  >> "$@VM🄲OA🄲.swift"
    echo "}"  >> "$@VM🄲OA🄲.swift"
    
    touch "$@VM🄲OD🄲.swift"
    echo "//" >> "$@VM🄲OD🄲.swift"
    echo "// $@VM🄲OD🄲" >> "$@VM🄲OD🄲.swift"
    echo "// $now"  >> "$@VM🄲OD🄲.swift"
    echo "//"  >> "$@VM🄲OD🄲.swift"
    echo ""  >> "$@VM🄲OD🄲.swift"
    echo "import Foundation"  >> "$@VM🄲OD🄲.swift"
    echo ""  >> "$@VM🄲OD🄲.swift"
    echo "class $@VM🄲OD🄲: OutputData {"  >> "$@VM🄲OD🄲.swift"
    echo "}"  >> "$@VM🄲OD🄲.swift"
    
    touch "$@VM🄲PA🄲.swift"
    echo "//" >> "$@VM🄲PA🄲.swift"
    echo "// $@VM🄲PA🄲" >> "$@VM🄲PA🄲.swift"
    echo "// $now"  >> "$@VM🄲PA🄲.swift"
    echo "//"  >> "$@VM🄲PA🄲.swift"
    echo ""  >> "$@VM🄲PA🄲.swift"
    echo "import Foundation"  >> "$@VM🄲PA🄲.swift"
    echo ""  >> "$@VM🄲PA🄲.swift"
    echo "class $@VM🄲PA🄲: PrivateActions {"  >> "$@VM🄲PA🄲.swift"
    echo "}"  >> "$@VM🄲PA🄲.swift"
    
    touch "$@VM🄲PD🄲.swift"
    echo "//" >> "$@VM🄲PD🄲.swift"
    echo "// $@VM🄲PD🄲" >> "$@VM🄲PD🄲.swift"
    echo "// $now"  >> "$@VM🄲PD🄲.swift"
    echo "//"  >> "$@VM🄲PD🄲.swift"
    echo ""  >> "$@VM🄲PD🄲.swift"
    echo "import Foundation"  >> "$@VM🄲PD🄲.swift"
    echo ""  >> "$@VM🄲PD🄲.swift"
    echo "class $@VM🄲PD🄲: PrivateData {"  >> "$@VM🄲PD🄲.swift"
    echo "}"  >> "$@VM🄲PD🄲.swift"
    cd ../../../../../
    ruby addFileToProject.rb $@ 
}
